"""initialmigration

Revision ID: 8bcda460e39c
Revises: aad6f3f5a43f
Create Date: 2017-05-03 15:50:17.509000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bcda460e39c'
down_revision = 'aad6f3f5a43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('users', 'avatar_default')
    #op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    #op.add_column('users', sa.Column('avatar_default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    pass